language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - mysql -e 'create database test_db;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan config:cache
  - php artisan migrate --database mysql_test

script:
  - vendor/bin/phpunit